### ISSUE TITLE
Version number for setup.py in git does not correspond to pypi release

### ISSUE THREAD

**Issue by proycon** [cltl/KafNafParserPy#21]
I checked the release history for this project on PyPi: https://pypi.org/project/KafNafParserPy/#history
This latest PyPI release is by definition the one included in LaMachine by the way.

It states the last release was on Jul 2017, and there have only been a few commits since I see, but the version number in ``setup.py`` seems older (Aug 2016), this raises some confusion to the current state of the software (it makes me worry whether there are changes that are not in git). A new release might be due to remedy this?

**Comment by antske** [comment]
latest setup.py update in github
